export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Next.js Project",
  description: "Generated by create next app",
  navItems: [
    {
      label: "Home",
      href: "/",
    },
  ],
  links: {
    github: "https://github.com",
    docs: "https://nextjs.org/docs",
  },
};

export const siteMetadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.name}`,
  },
  description: siteConfig.description,
  icons: {
    icon: "/favicon.ico",
  },
};
